minkphp/MinkSelenium2Driver

tests/Custom/WindowNameTest.php
While the Firefox driver uses lowercase letters, the Chrome driver is using uppercase letters in the window name (yeah, I started running the testsuite with chromium rather than using firefox because of the Firefox 35 issue).
=> Fix the window name test for the chrome driver

src/Selenium2Driver.php
Timeouts are in milliseconds, rather than microseconds.
Milliseconds are defined here: https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/Session.php#L320
=> Fix comment for setTimeouts

tests/Custom/TimeoutTest.php
This avoid fatal errors when the element is not found, allowing the other tests to run.
This fatal error happens currently in PhantomJS builds
=> Add safeguard for not found elements in the driver-specific tests

src/Selenium2Driver.php
To avoid having to redefine all defaults in config.
=> Join desired & default capabilities

.travis.yml, composer.json, phpunit.xml.dist, tests/Selenium2Config.php
This updates the testsuite to use https://github.com/minkphp/driver-testsuite
TODOs:
=> Update the testsuite to use the new mink/driver-testsuite

phpunit.xml.dist
They should reference the new driver-testsuite package, not the old testsuite available in Mink, as it will be removed.
=> Fix the path to tests

src/Selenium2Driver.php
Closes https://github.com/minkphp/MinkSelenium2Driver/issues/243
=> Fixed unwanted trailing tab in chrome 53

.travis.yml, bin/run-selenium-remote.sh, src/Selenium2Driver.php
Here's a proposed fix for #187. This works both on local and remote instances. I tested using a local installation of Selenium and a Docker instance.
=> Issue #187: Add support for uploading files to remote Selenium instance

src/Selenium2Driver.php
This fixes the remarks made by @stof on #252. This is split off in a new PR since #252 is already merged.
=> Fix review remarks. Followup for #252.

.travis.yml
Forcing a source install made the persistence of the composer download cache between builds useless, as we don't download packages.
No other (maintained) Mink repository is using ``--prefer-source`` on Travis. This one should not either.
=> Fix the usage of the composer cache on Travis

bin/run-selenium.sh
The travis installation steps will give enough time because opening firefox anyway.
Replaces #251
=> Avoid sleeping when starting xvfb

tests/Custom/WindowNameTest.php
GeckoDriver does not put a UUID in its window names.
=> Fix the window name tests for GeckoDriver

src/Selenium2Driver.php
moveto is not part of the W3C Webdriver spec, and so GeckoDriver does not implement it.
Our click() implementation uses it to ensure that the element is scrolled into the viewport before clicking on it, due to Selenium requirements.
Instead of forbidding the click entirely when using Geckodriver, this now attempts the click directly when moving is unsupported, hoping that the driver has not implemented the restriction when they don't have a way to force the move yet.
Refs #254
Other methods using ``moveto`` are not changed like this as they rely on the cursor position too (when using other non-standardized APIs).
Before:
Tests: 171, Assertions: 300, Errors: 46, Failures: 4, Skipped: 14.
After:
Tests: 172, Assertions: 375, Errors: 11, Failures: 6, Skipped: 13.
(and one of the failures and …
=> Improve compatibility with GeckoDriver when using Selenium 3

tests/Selenium2Config.php
Needed when minkphp/driver-testsuite#10 gets merged.
=> Skip testWindowMaximizeBeforePageVisit when using xvfb

tests/Custom/DesiredCapabilitiesTest.php, tests/Custom/WebDriverTest.php, tests/Custom/WindowNameTest.php
The session is not started anymore when getting it in the test. It requires starting it explicitly to test the case of setting capabilities after starting.
=> Rewrite the capability test to be compatible with lazy-starting

src/Selenium2Driver.php
Setting capabilities specifying a firefox version or a selenium version by default breaks when running against a server being strict about the requested capabilities (as it is unlikely to run Firefox 9 these days).
Note that I faced this issue when trying to run tests against geckodriver (as it is strict about respecting the Firefox version, unlike the old FirefoxDriver of Selenium 2).
=> Clean default capabilities

tests/Custom/WindowNameTest.php
Selenium defines the window name as a opaque string, so each browser is free to use anything they want. And this changed over time, causing the UUID regex to break even for browsers using a UUID in the past (Chrome adds more things around the UUID for instance).
=> Rewrite the window name tests to avoid forcing a pattern

tests/Custom/TimeoutTest.php
If the session is not started, the timeout is not applied on the webdriver session (as it does not exist at that point). Failures happen only when applying the timeout on the session.
That's a test I missed in #278 when fixing other tests which were dependant on the implicit start during `getSession()`
=> Fix the test about setting invalid timeout

.travis.yml
- remove testing on HHVM, as they stopped caring about PHP compat
- use the precise infra to run tests on PHP 5.3 (until we drop support, which is not the goal here)
- add testing on PHP 7.2
- use the tested PHP version to run the builtin webserver, as the Trusty infra may not pre-install PHP 5.6 (except for the 5.3 job of course, but that one runs on Precise)
=> Fix some Travis issues

.travis.yml
Env variables defined as matrix are not merged with the job env variables of the matrix. We need to use global env variables (which we can still override in a specific job if needed).
This fixes this error: https://travis-ci.org/minkphp/MinkSelenium2Driver/jobs/436675862#L167
=> Fix the configuration of the PHP 5.3 job on precise

src/Selenium2Driver.php
In relation with the issue #293, this change allow keep in the array chrome capabilites all options set into the behat configuration (key `default.extensions.Behat\MinkExtension.sessions.selenium2.capabilities.extra_capabilities.chromeOptions`)
Now if you set this option:
```
extensions:
Behat\MinkExtension:
selenium2:
capabilities: { "browser": "chrome", "browserName": "chrome", "extra_capabilities": { "chromeOptions": { "w3c": false } } }
```
The option will be send for the session option with ChromeDriver 75.0.3770.8+
=> Keep the chromeOptions array from configuration (w3c options)

CHANGELOG.md, README.md, composer.json, src/Resources/syn.js
1.4.0 / 2019-08-28
==================
Bug fixes:
* Don't use TABs, when triggering `change` JS event upon input value is change (fixes auto-complete control testing in Google Chrome)
* Fixed inability to manipulate windows when Selenium 3 with Firefox GeckoDriver was used
* The `clickOnElement` method wasn't working when Selenium 3 with Firefox GeckoDriver was used
Changes:
* Bumped requirement to PHP 5.4
New features:
* Allow uploading files to remote Selenium instances (e.g. SauceLabs, BrowserStack, etc.)
* Added `getDesiredCapabilities` method for fetching current desired capabilities
Testsuite:
* Don't test on PHP 5.3 (driver itself would likely continue to work on PHP 5.3 for some time)
* Adding testing on PHP 7.1, 7.2, 7.3 and 7.4beta
* Removed PhantomJS
Misc:
* Syn library is …
=> New Release

src/Selenium2Driver.php
In \Behat\Mink\Driver\Selenium2Driver::wait we always wait even if the condition returns true. This results in unnecessary waiting.
=> Only wait when necessary

.travis.yml
Fixing issue with xDebug 3 (used on PHP 7.3 and PHP 7.4) build fails due coverage collection not enabled in the xDebug.
=> Enable xDebug 3 support during build

src/Selenium2Driver.php
Some websites using a SPA approach have implemented behavior where when a correct value is entered into an input, it is immediately recognized and the SPA updates instantly, causing the input to be detached from the DOM.
e.g. a 2FA input field that immediately recognizes the correct value as it is typed, and causes the SPA to update the page instantly if it is correct.
When this happens, the input is set correctly via the `$element->postValue()` call from `setValue()`, but when it then proceeds to call `$this->executeJsOnElement()`, a StaleElementException is thrown because the input is no longer attached to the DOM.
Catch and swallow the exception.
It is not possible to execute JS on an element that is detached from the DOM, so it is impossible to attempt to unfocus it at this point (at …
=> Fix StaleElementException in setValue when input has gone away

tests/Selenium2Config.php
This test is not passing for Selenium2Driver, and other basic auth tests are already skipped.
Closes #347
=> Skip the BasicAuth test asserting auth in URL

CHANGELOG.md, src/Resources/syn.js, src/Selenium2Driver.php
syn.js downloaded by `npm install syn` and moved from `node_modules/syn/dist/global/syn.js` (no local compilation, only non-minified version is available, thankfully, as it is much better for debugging)
replaces https://github.com/minkphp/MinkSelenium2Driver/pull/333
fixes #279 and maybe also #20
=> Upgrade JS syn to v0.15.0

.github/workflows/tests.yml
this is useful if we want to try a new version of the driver testsuite with the driver.
=> Add the possibility to trigger a CI run manually

src/Selenium2Driver.php
This case now throws a DriverException instead of triggering a PHP Fatal Error.
Closes https://github.com/minkphp/Mink/issues/679
This was not caught by phpstan initially due to the incomplete type on the `wdSession` property.
=> Add proper handling of non-started sessions

composer.json, src/Selenium2Driver.php
Now that the Mink DriverInterface has parameter types (thanks to https://github.com/minkphp/Mink/pull/856), we can add them in the child class.
=> Add types for method parameters

README.md
The usage example in the README.md file is quite outdated:
* it has a `Selenium\Client` class import (likely from Selenium 1 driver), that doesn't exist in this driver
* it specifies the page URL in place of the WebDriver host URL
* no page is actually opened
* the Composer autoload.php file isn't included, which results in a Fatal error
The provided example might actually be working.
=> Correct usage example in the README.md

src/Selenium2Driver.php
Closes https://github.com/minkphp/MinkSelenium2Driver/issues/379
Added code remains uncovered by tests because we're testing on Selenium 2 only.
=> Improve "Selenium2Driver::applyTimeouts" error handling for Selenium 3 support

src/Selenium2Driver.php
Fixes this error from the https://github.com/minkphp/MinkSelenium2Driver/pull/383:
```
Behat\Mink\Tests\Driver\Js\WindowTest::testWindow
WebDriver\Exception\NoSuchWindow: Unable to locate window:
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az697-197', ip: '10.1.0.44', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-10[56](https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049068?pr=383#step:8:57)-azure', java.version: '1.8.0_292'
Driver info: driver.version: unknown
```
Implementation ported from the https://github.com/minkphp/webdriver-classic-driver.
What's included:
1. [fixed] switching to window by name on Selenium 3
2. [fixed] window resizing and maximizing for a non-current window
3. …
=> Fixing window switching on Selenium 3

src/Selenium2Driver.php
Fixes this error from the https://github.com/minkphp/MinkSelenium2Driver/pull/383:
```
Behat\Mink\Tests\Driver\Basic\IFrameTest::testIFrame
WebDriver\Exception\InvalidArgument: data did not match any variant of untagged enum FrameId at line 3 column 1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az779-213', ip: '10.1.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1056-azure', java.version: '1.8.0_[29](https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049622?pr=383#step:8:30)2'
Driver info: driver.version: unknown
```
Implementation ported from the https://github.com/minkphp/webdriver-classic-driver.
It appears, that on Selenium 3 frame switching is possible only by index or …
=> Fixed frame switching by name on Selenium 3

.github/workflows/tests.yml
Used `selenium/standalone-firefox` Docker image chooses the Firefox version like so:
* Selenium 2.53.1 = Firefox 47
* Selenium 3.141.59 = Firefox 92
Not sure why, but some of the below tests fail only on Firefox 92.
https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049068?pr=383
> 1) Behat\Mink\Tests\Driver\Basic\IFrameTest::testIFrame
WebDriver\Exception\InvalidArgument: data did not match any variant of untagged enum FrameId at line 3 column 1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az779-213', ip: '10.1.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1056-azure', java.version: '1.8.0_[29](https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049622?p …
=> Also test on Selenium 3

src/Selenium2Driver.php
This is based on the https://github.com/minkphp/webdriver-classic-driver/pull/32 .
The `JavascriptTest::testDragDropOntoHiddenItself` test was failing before this PR.
* Closes #362
* Closes #193
=> Fixing "getText" method returning an empty value on a visible element

src/Selenium2Driver.php
This fixes dragging over itself, ie. source element = destination element, in such usecase, extra `WebDriver\Session::moveto()` call is redundant.
Drag library like https://github.com/Shopify/draggable needs this fix as the source element is very often transformed when dragging and `WebDriver\Session::moveto()` is failing otherwise.
also remove `Selenium2Driver::withSyn()` call as completely useless for dragging, the current impl. of `Selenium2Driver::dragTo()` does not use it
=> No WebDriver\Session::moveto() call when dragging onto itself

src/Selenium2Driver.php, tests/Custom/TimeoutTest.php
1. Instead of supplying developer-provided timeout type directly to the Selenium Server as-is perform some validation as done in https://github.com/minkphp/webdriver-classic-driver .
2. Wrap WebDriver's `TimeoutException` and `ScriptTimeoutException` exceptions into `DriverException`, when the page wasn't opened due to `page load`/`pageLoad` timeout being met.
3. The `pageLoad` timeout wasn't working with Google Chrome on Selenium Server 3.
Closes #397
=> Rewrite timeout handling code to support Selenium Server 3

.github/workflows/tests.yml, tests/Selenium2Config.php
=> Skip "testDragDropOntoHiddenItself" test on Selenium 2 + Firefox

.github/workflows/tests.yml
Speed up build by collecting coverage only based on Selenium version difference.
=> Collect coverage only once per Selenium Server version

.github/workflows/tests.yml, docker-compose.yml
Ported some changes from `webdriver-classic-driver`.
=> Use "docker-composer.yml" file during the build

.github/workflows/tests.yml, src/Selenium2Driver.php, tests/Custom/SeleniumSupportTest.php, tests/Custom/WebDriverTest.php, tests/Selenium2Config.php
=> Inform developers about non-working "rightClick" on Selenium Server 3.x

docker-compose.yml
I missed this in the original PR. This driver cannot work with Selenium 4 at all, so it makes sense to use a supported default version, if for anything to avoid confusing users.
=> Use selenium 2 as the default version
